#if UNITY_EDITOR
using System;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEditor.Callbacks;

namespace Game.Core.Managers.Dependency.Editor
{
    public static class DependencyRegistryGenerator
    {
        private const string OutputPath = "Assets/@Scripts/Core/Manager/Dependency/Generated/DependencyRegistry.g.cs";

        [MenuItem("Tools/Generates/Dependency Registry")]
        public static void Generate()
        {
            Type[] dependencyTypes = TypeCache
                .GetTypesWithAttribute<DependencyAttribute>()
                .Where(t => t != null)
                .Where(t => !t.IsAbstract)
                .Where(t => !t.IsInterface)
                .OrderBy(t => t.FullName, StringComparer.Ordinal)
                .ToArray();

            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This file is generated by DependencyRegistryGenerator.");
            sb.AppendLine("// Do not edit manually.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine();
            sb.AppendLine("namespace Game.Core.Managers.Dependency.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    public readonly struct DependencyDescriptor");
            sb.AppendLine("    {");
            sb.AppendLine("        public DependencyDescriptor(Type type, bool isGlobal, string sceneName)");
            sb.AppendLine("        {");
            sb.AppendLine("            Type = type;");
            sb.AppendLine("            IsGlobal = isGlobal;");
            sb.AppendLine("            SceneName = sceneName;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public Type Type { get; }");
            sb.AppendLine("        public bool IsGlobal { get; }");
            sb.AppendLine("        public string SceneName { get; }");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public static class DependencyRegistry");
            sb.AppendLine("    {");
            sb.AppendLine("        public static readonly DependencyDescriptor[] All =");
            sb.AppendLine("        {");

            foreach (Type dependencyType in dependencyTypes)
            {
                DependencyAttribute attribute = dependencyType.GetCustomAttributes(typeof(DependencyAttribute), false)
                    .Cast<DependencyAttribute>()
                    .First();

                Validate(dependencyType, attribute);

                string typeName = GetGlobalTypeName(dependencyType);
                string sceneNameValue = attribute.SceneName != null
                    ? $"\"{attribute.SceneName}\""
                    : "null";
                string isGlobalValue = attribute.IsGlobal ? "true" : "false";

                sb.AppendLine($"            new(typeof({typeName}), {isGlobalValue}, {sceneNameValue}),");
            }

            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            EnsureParentDirectory(OutputPath);

            string newContent = sb.ToString();
            string oldContent = File.Exists(OutputPath) ? File.ReadAllText(OutputPath) : string.Empty;
            if (string.Equals(oldContent, newContent, StringComparison.Ordinal))
                return;

            File.WriteAllText(OutputPath, newContent, new UTF8Encoding(false));
            AssetDatabase.Refresh();

            UnityEngine.Debug.Log($"[DependencyRegistryGenerator] Generated {dependencyTypes.Length} dependencies to {OutputPath}");
        }

        [DidReloadScripts]
        private static void OnScriptsReloaded()
        {
            Generate();
        }

        private static void Validate(Type dependencyType, DependencyAttribute attribute)
        {
            if (!attribute.IsGlobal && string.IsNullOrWhiteSpace(attribute.SceneName))
            {
                throw new InvalidOperationException(
                    $"Dependency '{dependencyType.FullName}' must be global or declare a scene name.");
            }

            if (!attribute.IsGlobal)
            {
                Type[] sceneTypes = TypeCache
                    .GetTypesDerivedFrom<object>()
                    .Where(t => t != null)
                    .Where(t => string.Equals(t.Name, attribute.SceneName, StringComparison.Ordinal))
                    .ToArray();

                if (sceneTypes.Length == 0)
                {
                    throw new InvalidOperationException(
                        $"Dependency '{dependencyType.FullName}' scene '{attribute.SceneName}' could not be resolved.");
                }

                if (sceneTypes.Length > 1)
                {
                    throw new InvalidOperationException(
                        $"Dependency '{dependencyType.FullName}' scene '{attribute.SceneName}' is ambiguous.");
                }
            }

            if (dependencyType.GetConstructors(global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic)
                .All(ctor => ctor.GetParameters().Length != 0))
            {
                throw new InvalidOperationException(
                    $"Dependency '{dependencyType.FullName}' must have a parameterless constructor.");
            }
        }

        private static string GetGlobalTypeName(Type type)
        {
            return "global::" + type.FullName!.Replace("+", ".");
        }

        private static void EnsureParentDirectory(string filePath)
        {
            string directory = Path.GetDirectoryName(filePath);
            if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }
        }
    }
}
#endif
