#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Game.Core.Managers;
using UnityEditor;

namespace Game.Core.Manager.Editor
{
    public static class ManagerRegistryGenerator
    {
        private const string OutputPath = "Assets/@Scripts/Core/Manager/Generated/ManagerRegistry.g.cs";

        [MenuItem("Tools/Generates/Manager Registry")]
        public static void Generate()
        {
            Type[] managerTypes = TypeCache
                .GetTypesDerivedFrom(typeof(BaseManager<>))
                .Where(t => t != null)
                .Where(t => !t.IsAbstract)
                .OrderBy(t => t.FullName, StringComparer.Ordinal)
                .ToArray();

            managerTypes = SortByDependencies(managerTypes);

            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This file is generated by ManagerRegistryGenerator.");
            sb.AppendLine("// Do not edit manually.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine();
            sb.AppendLine("namespace Game.System.Core.Manager");
            sb.AppendLine("{");
            sb.AppendLine("    public readonly struct ManagerDescriptor");
            sb.AppendLine("    {");
            sb.AppendLine("        public ManagerDescriptor(Type type, Action create, Action init, Action postInit, Action dispose)");
            sb.AppendLine("        {");
            sb.AppendLine("            Type = type;");
            sb.AppendLine("            Create = create;");
            sb.AppendLine("            Init = init;");
            sb.AppendLine("            PostInit = postInit;");
            sb.AppendLine("            Dispose = dispose;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public Type Type { get; }");
            sb.AppendLine("        public Action Create { get; }");
            sb.AppendLine("        public Action Init { get; }");
            sb.AppendLine("        public Action PostInit { get; }");
            sb.AppendLine("        public Action Dispose { get; }");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public static class ManagerRegistry");
            sb.AppendLine("    {");
            sb.AppendLine("        public static readonly ManagerDescriptor[] All =");
            sb.AppendLine("        {");

            foreach (Type managerType in managerTypes)
            {
                string fullName = GetGlobalTypeName(managerType);
                sb.AppendLine($"            new(typeof({fullName}), {fullName}.Create, {fullName}.Init, {fullName}.PostInit, {fullName}.Dispose),");
            }

            sb.AppendLine("        };");
            sb.AppendLine();
            sb.AppendLine("        public static void AllInit()");
            sb.AppendLine("        {");
            sb.AppendLine("            for (int i = 0; i < All.Length; i++)");
            sb.AppendLine("            {");
            sb.AppendLine("                All[i].Create();");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            for (int i = 0; i < All.Length; i++)");
            sb.AppendLine("            {");
            sb.AppendLine("                All[i].Init();");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            for (int i = 0; i < All.Length; i++)");
            sb.AppendLine("            {");
            sb.AppendLine("                All[i].PostInit();");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static void AllDispose()");
            sb.AppendLine("        {");
            sb.AppendLine("            for (int i = All.Length - 1; i >= 0; i--)");
            sb.AppendLine("            {");
            sb.AppendLine("                All[i].Dispose();");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            EnsureParentDirectory(OutputPath);
            File.WriteAllText(OutputPath, sb.ToString(), new UTF8Encoding(false));
            AssetDatabase.Refresh();

            UnityEngine.Debug.Log($"[ManagerRegistryGenerator] Generated {managerTypes.Length} managers to {OutputPath}");
        }

        private static string GetGlobalTypeName(Type type)
        {
            return "global::" + type.FullName!.Replace("+", ".");
        }

        private enum VisitState
        {
            None,
            Visiting,
            Visited,
        }

        private static Type[] SortByDependencies(Type[] managerTypes)
        {
            HashSet<Type> managerSet = managerTypes.ToHashSet();
            Dictionary<Type, VisitState> states = managerTypes.ToDictionary(
                managerType => managerType,
                _ => VisitState.None);
            List<Type> sorted = new List<Type>();
            Stack<Type> path = new Stack<Type>();

            for (int i = 0; i < managerTypes.Length; i++)
            {
                Visit(managerTypes[i], managerSet, states, sorted, path);
            }

            return sorted.ToArray();
        }

        private static void Visit(
            Type managerType,
            HashSet<Type> managerSet,
            Dictionary<Type, VisitState> states,
            List<Type> sorted,
            Stack<Type> path)
        {
            VisitState state = states[managerType];

            if (state == VisitState.Visited)
                return;

            if (state == VisitState.Visiting)
            {
                string cycle = string.Join(" -> ", path.Reverse().Select(type => type.Name));
                throw new InvalidOperationException($"Manager dependency cycle detected: {cycle} -> {managerType.Name}");
            }

            states[managerType] = VisitState.Visiting;
            path.Push(managerType);

            Type[] dependencies = GetDependencies(managerType);
            for (int i = 0; i < dependencies.Length; i++)
            {
                Type dependencyType = dependencies[i];

                if (!managerSet.Contains(dependencyType))
                {
                    throw new InvalidOperationException(
                        $"Manager dependency is not registered. {managerType.FullName} depends on {dependencyType.FullName}");
                }

                Visit(dependencyType, managerSet, states, sorted, path);
            }

            path.Pop();
            states[managerType] = VisitState.Visited;
            sorted.Add(managerType);
        }

        private static Type[] GetDependencies(Type managerType)
        {
            return managerType
                .GetCustomAttributes(typeof(ManagerDependencyAttribute), false)
                .Cast<ManagerDependencyAttribute>()
                .Select(attribute => attribute.ManagerType)
                .ToArray();
        }

        private static void EnsureParentDirectory(string filePath)
        {
            string directory = Path.GetDirectoryName(filePath);
            if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }
        }
    }
}
#endif
