#if UNITY_EDITOR
using System;
using System.IO;
using System.Linq;
using System.Text;
using Game.Core.Managers;
using UnityEditor;

namespace Game.Core.Manager.Editor
{
    public static class ManagerRegistryGenerator
    {
        private const string OutputPath = "Assets/@Scripts/Core/Manager/Generated/ManagerRegistry.g.cs";

        [MenuItem("Tools/Generates/Manager Registry")]
        public static void Generate()
        {
            Type[] managerTypes = TypeCache
                .GetTypesDerivedFrom(typeof(BaseManager<>))
                .Where(t => t != null)
                .Where(t => !t.IsAbstract)
                .OrderBy(t => t.FullName, StringComparer.Ordinal)
                .ToArray();

            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This file is generated by ManagerRegistryGenerator.");
            sb.AppendLine("// Do not edit manually.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine();
            sb.AppendLine("namespace Game.System.Core.Manager");
            sb.AppendLine("{");
            sb.AppendLine("    public readonly struct ManagerDescriptor");
            sb.AppendLine("    {");
            sb.AppendLine("        public ManagerDescriptor(Type type, Action init, Action dispose)");
            sb.AppendLine("        {");
            sb.AppendLine("            Type = type;");
            sb.AppendLine("            Init = init;");
            sb.AppendLine("            Dispose = dispose;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public Type Type { get; }");
            sb.AppendLine("        public Action Init { get; }");
            sb.AppendLine("        public Action Dispose { get; }");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public static class ManagerRegistry");
            sb.AppendLine("    {");
            sb.AppendLine("        public static readonly ManagerDescriptor[] All =");
            sb.AppendLine("        {");

            foreach (Type managerType in managerTypes)
            {
                string fullName = GetGlobalTypeName(managerType);
                sb.AppendLine($"            new(typeof({fullName}), {fullName}.Init, {fullName}.Dispose),");
            }

            sb.AppendLine("        };");
            sb.AppendLine();
            sb.AppendLine("        public static void AllInit()");
            sb.AppendLine("        {");
            sb.AppendLine("            for (int i = 0; i < All.Length; i++)");
            sb.AppendLine("            {");
            sb.AppendLine("                All[i].Init();");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public static void AllDispose()");
            sb.AppendLine("        {");
            sb.AppendLine("            for (int i = All.Length - 1; i >= 0; i--)");
            sb.AppendLine("            {");
            sb.AppendLine("                All[i].Dispose();");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            EnsureParentDirectory(OutputPath);
            File.WriteAllText(OutputPath, sb.ToString(), new UTF8Encoding(false));
            AssetDatabase.Refresh();

            UnityEngine.Debug.Log($"[ManagerRegistryGenerator] Generated {managerTypes.Length} managers to {OutputPath}");
        }

        private static string GetGlobalTypeName(Type type)
        {
            return "global::" + type.FullName!.Replace("+", ".");
        }

        private static void EnsureParentDirectory(string filePath)
        {
            string directory = Path.GetDirectoryName(filePath);
            if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }
        }
    }
}
#endif
