#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Game.Data;
using UnityEditor;
using UnityEngine;
using Object = UnityEngine.Object;

namespace Game.Core.Manager.Editor
{
    public static class ModelEnumGenerator
    {
        private const string TableSearchRoot = "Assets/@Resources";
        private const string OutputDirectory = "Assets/@Scripts/Generated";
        private const string GeneratedPrefix = "E";
        private const string GeneratedSuffix = ".g.cs";

        [MenuItem("Tools/Generates/Model Enum")]
        public static void Generate()
        {
            Directory.CreateDirectory(OutputDirectory);

            Dictionary<string, string> outputs = CollectEnumOutputs();
            DeleteStaleGeneratedFiles(outputs.Keys);

            foreach (KeyValuePair<string, string> pair in outputs)
            {
                File.WriteAllText(pair.Key, pair.Value, new UTF8Encoding(false));
            }

            AssetDatabase.Refresh();
        }

        private static Dictionary<string, string> CollectEnumOutputs()
        {
            Dictionary<string, string> outputs = new Dictionary<string, string>();
            string[] guids = AssetDatabase.FindAssets("t:ScriptableObject", new[] { TableSearchRoot });

            for (int i = 0; i < guids.Length; i++)
            {
                string assetPath = AssetDatabase.GUIDToAssetPath(guids[i]);
                ScriptableObject tableAsset = AssetDatabase.LoadAssetAtPath<ScriptableObject>(assetPath);
                if (tableAsset == null)
                    continue;

                Type tableType = tableAsset.GetType();
                if (!TryGetRowType(tableType, out Type rowType))
                    continue;

                string enumName = BuildEnumName(rowType);
                string outputPath = Path.Combine(OutputDirectory, enumName + GeneratedSuffix).Replace('\\', '/');
                outputs[outputPath] = BuildEnumSource(enumName, tableAsset);
            }

            return outputs;
        }

        private static bool TryGetRowType(Type tableType, out Type rowType)
        {
            Type current = tableType;
            while (current != null)
            {
                if (current.IsGenericType && current.GetGenericTypeDefinition() == typeof(AbstractTable<,>))
                {
                    rowType = current.GetGenericArguments()[0];
                    return true;
                }

                current = current.BaseType;
            }

            rowType = null;
            return false;
        }

        private static string BuildEnumName(Type rowType)
        {
            string rowTypeName = rowType.Name;
            if (rowTypeName.EndsWith("Model", StringComparison.Ordinal))
            {
                rowTypeName = rowTypeName.Substring(0, rowTypeName.Length - "Model".Length);
            }

            return GeneratedPrefix + rowTypeName;
        }

        private static string BuildEnumSource(string enumName, ScriptableObject table)
        {
            SerializedObject serializedTable = new SerializedObject(table);
            SerializedProperty rows = serializedTable.FindProperty("_rows");

            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This file is generated by ModelEnumGenerator.");
            sb.AppendLine("// Do not edit manually.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("namespace Game.Generated");
            sb.AppendLine("{");
            sb.AppendLine($"    public enum {enumName}");
            sb.AppendLine("    {");

            for (int i = 0; i < rows.arraySize; i++)
            {
                Object row = rows.GetArrayElementAtIndex(i).objectReferenceValue;
                string enumValueName = row != null ? row.name : $"Unknown{i}";
                enumValueName = RemoveKnownPrefixes(enumValueName);
                enumValueName = SanitizeName(enumValueName);
                sb.AppendLine($"        {enumValueName} = {i},");
            }

            sb.AppendLine($"        Count = {rows.arraySize},");

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void DeleteStaleGeneratedFiles(IEnumerable<string> validOutputPaths)
        {
            HashSet<string> validPaths = new HashSet<string>(validOutputPaths.Select(path => path.Replace('\\', '/')), StringComparer.OrdinalIgnoreCase);

            if (!Directory.Exists(OutputDirectory))
                return;

            string[] existingFiles = Directory.GetFiles(OutputDirectory, GeneratedPrefix + "*" + GeneratedSuffix, SearchOption.TopDirectoryOnly);
            for (int i = 0; i < existingFiles.Length; i++)
            {
                string normalizedPath = existingFiles[i].Replace('\\', '/');
                if (validPaths.Contains(normalizedPath))
                    continue;

                string metaPath = normalizedPath + ".meta";
                File.Delete(existingFiles[i]);
                if (File.Exists(metaPath))
                {
                    File.Delete(metaPath);
                }
            }
        }

        private static string SanitizeName(string raw)
        {
            string sanitized = new string(raw.Where(char.IsLetterOrDigit).ToArray());
            if (string.IsNullOrEmpty(sanitized))
            {
                sanitized = "Unknown";
            }

            if (char.IsDigit(sanitized[0]))
            {
                sanitized = "_" + sanitized;
            }

            return sanitized;
        }

        private static string RemoveKnownPrefixes(string raw)
        {
            string[] prefixes =
            {
                "Character_",
                "Skill_",
                "SaveFile_"
            };

            for (int i = 0; i < prefixes.Length; i++)
            {
                if (raw.StartsWith(prefixes[i], StringComparison.Ordinal))
                {
                    return raw.Substring(prefixes[i].Length);
                }
            }

            return raw;
        }
    }
}
#endif
