#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Game.Core.Managers.Dependency;
using Game.Data;
using UnityEditor;
using UnityEditor.Callbacks;

namespace Game.Core.Managers.Save.Editor
{
    public static class SaveRegistryGenerator
    {
        private const string OutputPath = "Assets/@Scripts/Core/Manager/Save/Generated/SaveRegistry.g.cs";
        private const string CatalogPath = "Assets/@Resources/Data/SaveCatalog.asset";

        [MenuItem("Tools/Generates/Save Registry")]
        public static void Generate()
        {
            SaveCatalogModel catalog = LoadCatalog();
            if (catalog == null)
                return;

            SaveCatalogEntry[] entries = GetEntries(catalog);

            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// This file is generated by SaveRegistryGenerator.");
            sb.AppendLine("// Do not edit manually.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine();
            sb.AppendLine("namespace Game.Core.Managers.Save");
            sb.AppendLine("{");
            sb.AppendLine("    public readonly struct SaveDescriptor");
            sb.AppendLine("    {");
            sb.AppendLine("        public SaveDescriptor(string fileName, string sectionName, Action<SaveManager> register)");
            sb.AppendLine("        {");
            sb.AppendLine("            FileName = fileName;");
            sb.AppendLine("            SectionName = sectionName;");
            sb.AppendLine("            Register = register;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public string FileName { get; }");
            sb.AppendLine("        public string SectionName { get; }");
            sb.AppendLine("        public Action<SaveManager> Register { get; }");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public static class SaveRegistry");
            sb.AppendLine("    {");
            sb.AppendLine("        public static readonly SaveDescriptor[] All =");
            sb.AppendLine("        {");

            for (int i = 0; i < entries.Length; i++)
            {
                SaveCatalogEntry entry = entries[i];

                string fileName = ToStringLiteral(entry.FileName);
                string sectionName = ToStringLiteral(entry.SectionName);
                sb.AppendLine($"            new({fileName}, {sectionName}, manager => manager.Register<{GetGlobalTypeName(entry.StateType)}, {GetGlobalTypeName(entry.SaveType)}>({fileName}, {sectionName})),");
            }

            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            EnsureParentDirectory(OutputPath);

            string newContent = sb.ToString();
            string oldContent = File.Exists(OutputPath) ? File.ReadAllText(OutputPath) : string.Empty;
            if (string.Equals(oldContent, newContent, StringComparison.Ordinal))
                return;

            File.WriteAllText(OutputPath, newContent, new UTF8Encoding(false));
            AssetDatabase.Refresh();

            UnityEngine.Debug.Log($"[SaveRegistryGenerator] Generated {entries.Length} save states to {OutputPath}");
        }

        [DidReloadScripts]
        private static void OnScriptsReloaded()
        {
            Generate();
        }

        private static string GetGlobalTypeName(Type type)
        {
            return "global::" + type.FullName!.Replace("+", ".");
        }

        private static SaveCatalogModel LoadCatalog()
        {
            SaveCatalogModel catalog = AssetDatabase.LoadAssetAtPath<SaveCatalogModel>(CatalogPath);
            if (catalog != null)
                return catalog;

            UnityEngine.Debug.LogWarning($"[SaveRegistryGenerator] SaveCatalogModel asset could not be found at {CatalogPath}.");
            return null;
        }

        private static SaveCatalogEntry[] GetEntries(SaveCatalogModel catalog)
        {
            List<SaveCatalogEntry> entries = new List<SaveCatalogEntry>();
            HashSet<string> keys = new HashSet<string>(StringComparer.Ordinal);
            HashSet<Type> stateTypes = new HashSet<Type>();

            for (int i = 0; i < catalog.Files.Count; i++)
            {
                SaveCatalogFile file = catalog.Files[i];
                if (string.IsNullOrWhiteSpace(file.FileName))
                    throw new InvalidOperationException("Save catalog file name is empty.");

                for (int j = 0; j < file.Sections.Count; j++)
                {
                    SaveCatalogSection section = file.Sections[j];
                    if (string.IsNullOrWhiteSpace(section.SectionName))
                        throw new InvalidOperationException($"Save catalog section name is empty. File: {file.FileName}");

                    Type stateType = section.StateType;
                    if (stateType == null)
                        throw new InvalidOperationException($"Save catalog state script is missing. File: {file.FileName}, Section: {section.SectionName}");

                    if (stateType.GetCustomAttributes(typeof(DependencyAttribute), false).Length == 0)
                    {
                        throw new InvalidOperationException(
                            $"Save catalog state must have DependencyAttribute. State: {stateType.FullName}");
                    }

                    Type saveInterface = stateType.GetInterfaces()
                        .FirstOrDefault(type => type.IsGenericType && type.GetGenericTypeDefinition() == typeof(ISave<>));
                    if (saveInterface == null)
                    {
                        throw new InvalidOperationException(
                            $"Save catalog state does not implement ISave<TSave>. State: {stateType.FullName}");
                    }

                    Type saveType = saveInterface.GetGenericArguments()[0];
                    string key = $"{file.FileName}:{section.SectionName}";
                    if (!keys.Add(key))
                    {
                        throw new InvalidOperationException(
                            $"Duplicate save catalog section. File: {file.FileName}, Section: {section.SectionName}");
                    }

                    if (!stateTypes.Add(stateType))
                    {
                        throw new InvalidOperationException(
                            $"Duplicate save catalog state. State: {stateType.FullName}");
                    }

                    entries.Add(new SaveCatalogEntry(
                        file.FileName,
                        section.SectionName,
                        stateType,
                        saveType));
                }
            }

            return entries
                .OrderBy(entry => entry.FileName, StringComparer.Ordinal)
                .ThenBy(entry => entry.SectionName, StringComparer.Ordinal)
                .ToArray();
        }

        private readonly struct SaveCatalogEntry
        {
            public SaveCatalogEntry(string fileName, string sectionName, Type stateType, Type saveType)
            {
                FileName = fileName;
                SectionName = sectionName;
                StateType = stateType;
                SaveType = saveType;
            }

            public string FileName { get; }
            public string SectionName { get; }
            public Type StateType { get; }
            public Type SaveType { get; }
        }

        private static string ToStringLiteral(string value)
        {
            return "\"" + value
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"") + "\"";
        }

        private static void EnsureParentDirectory(string filePath)
        {
            string directory = Path.GetDirectoryName(filePath);
            if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }
        }
    }
}
#endif
